apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - signalops-production-tls.yaml
  - signalops-istio-production-route.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/stage: production
      signalops.syncratic.io/production-cutover-allowed: "true"
