apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-connect-ingress
    namespace: signalops-connect
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: connect
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-connect-worker
    namespace: signalops-connect
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: connect
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-connect-outbox
    namespace: signalops-connect
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: connect
