apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-cyberops-normalizer
    namespace: signalops-cyberops
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: cyberops
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-cyberops-detector
    namespace: signalops-cyberops
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: cyberops
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-cyberops-materializer
    namespace: signalops-cyberops
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: cyberops
