apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-web
    namespace: signalops-app
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: app
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-gateway
    namespace: signalops-app
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: app
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-admin-notification-recorder
    namespace: signalops-app
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: app
