apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-keycloak
    namespace: signalops-identity
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: identity
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-keycloak-reconciler
    namespace: signalops-identity
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: identity
