apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-marketops-scheduler
    namespace: signalops-marketops
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: marketops
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-marketops-provider-worker
    namespace: signalops-marketops
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: marketops
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-marketops-analytics-worker
    namespace: signalops-marketops
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: marketops
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-marketops-saf-worker
    namespace: signalops-marketops
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: marketops
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-marketops-syncratic-worker
    namespace: signalops-marketops
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: marketops
