apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-pgbouncer
    namespace: signalops-data
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: data
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-broker-access
    namespace: signalops-data
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: data
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: signalops-backup-restore
    namespace: signalops-data
    labels:
      app.kubernetes.io/part-of: signalops
      signalops.syncratic.io/plane: data
