INSERT INTO catalog_pipelines (tenant_id, pipeline_id, source_id, source_domain, pipeline_name, description, status, stages, input_datasets, output_topics, metadata) VALUES
('tenant-local','pipeline-raw-normalizer','src-massive','market_data','Raw event normalizer','Normalizes provider raw events into the temporal ledger.','active',ARRAY['consume_raw','normalize','persist_normalized'],ARRAY['equity_eod_prices','option_contracts_daily'],ARRAY['signalops.local.normalized.v1'],'{"component":"normalizer"}'::jsonb),
('tenant-local','pipeline-signal-persister','src-signalops','platform','Signal persister','Persists normalized signals and lifecycle records.','active',ARRAY['consume_normalized','evaluate','persist_signal'],ARRAY['normalized_events'],ARRAY['signalops.local.signals.v1'],'{"component":"signal-persister"}'::jsonb),
('tenant-local','pipeline-replay-worker','src-signalops','platform','Replay worker','Replays selected raw events through normalization and persistence.','active',ARRAY['claim_job','replay','persist_result'],ARRAY['raw_event_ledger'],ARRAY['signalops.local.raw.v1'],'{"component":"replay-worker"}'::jsonb),
('tenant-local','pipeline-equity-reconciliation','src-massive','market_data','Equity reconciliation','Retries missing equity end-of-day observations after scheduled ingest.','active',ARRAY['detect_gap','provider_retry','normalize_barrier'],ARRAY['equity_eod_prices'],ARRAY['signalops.local.raw.v1'],'{"component":"massive-puller"}'::jsonb),
('tenant-local','pipeline-asset-backfill','src-massive','market_data','Asset backfill worker','Processes analyst-requested historical equity backfills sequentially.','active',ARRAY['claim_job','pull_history','normalize_barrier'],ARRAY['equity_eod_prices'],ARRAY['signalops.local.raw.v1'],'{"component":"marketops-asset-backfill-worker"}'::jsonb),
('tenant-local','pipeline-intraday-monitor','src-massive','market_data','Intraday condition monitor','Captures the latest 15-minute asset condition snapshot.','active',ARRAY['load_assets','quote_pull','condition_evaluation','persist_current'],ARRAY['equity_quote'],ARRAY[]::text[],'{"component":"marketops-intraday-monitor"}'::jsonb),
('tenant-local','pipeline-options-coverage','src-massive','market_data','Options coverage runner','Captures selected options-chain coverage and derived distributions.','active',ARRAY['load_assets','options_pull','derive_distribution','persist'],ARRAY['options_contracts_daily'],ARRAY[]::text[],'{"component":"marketops-options-coverage-runner"}'::jsonb),
('tenant-local','pipeline-options-features','src-massive','market_data','Options feature materializer','Materializes options features for research and algorithms.','active',ARRAY['load_options','derive_features','persist'],ARRAY['options_contracts_daily'],ARRAY[]::text[],'{"component":"marketops-options-feature-materializer"}'::jsonb),
('tenant-local','pipeline-market-state','src-marketops','market_data','Market State materializer','Builds persisted daily Market State from equity and options evidence.','active',ARRAY['load_evidence','materialize_state','persist'],ARRAY['equity_eod_prices','options_features'],ARRAY[]::text[],'{"component":"marketops-state-materializer"}'::jsonb),
('tenant-local','pipeline-hypothesis-evaluator','src-marketops','market_data','Hypothesis evaluator','Evaluates asset-specific research hypotheses from Market State.','active',ARRAY['load_state','evaluate_hypotheses','persist'],ARRAY['market_state'],ARRAY[]::text[],'{"component":"marketops-hypothesis-evaluator"}'::jsonb),
('tenant-local','pipeline-algorithm-runner','src-signalops','platform','Algorithm runner','Executes platform algorithms and persists independent observations.','active',ARRAY['load_features','run_algorithm','persist_observation'],ARRAY['feature_observations'],ARRAY[]::text[],'{"component":"algorithm-runner"}'::jsonb),
('tenant-local','pipeline-algorithm-adjudicator','src-signalops','platform','Algorithm adjudicator','Independently adjudicates MarketOps research evidence.','active',ARRAY['load_observations','adjudicate','persist'],ARRAY['algorithm_observations','hypothesis_evaluations'],ARRAY[]::text[],'{"component":"marketops-algorithm-adjudicator"}'::jsonb),
('tenant-local','pipeline-intelligence-cohort','src-marketops','market_data','Intelligence cohort runner','Runs state, hypotheses, opportunities, and outcomes for asset cohorts.','active',ARRAY['preflight','state','hypotheses','opportunities','outcomes'],ARRAY['market_state','feature_observations'],ARRAY[]::text[],'{"component":"marketops-intelligence-cohort-runner"}'::jsonb),
('tenant-local','pipeline-opportunity-builder','src-marketops','market_data','Opportunity builder','Builds research-only opportunities from evaluated hypotheses.','active',ARRAY['load_hypotheses','build_opportunity','persist'],ARRAY['hypothesis_evaluations'],ARRAY[]::text[],'{"component":"marketops-opportunity-builder"}'::jsonb),
('tenant-local','pipeline-outcome-materializer','src-marketops','market_data','Outcome materializer','Matures research outcomes against later market evidence.','active',ARRAY['load_origins','mature_outcome','persist'],ARRAY['market_state','equity_eod_prices'],ARRAY[]::text[],'{"component":"marketops-outcome-materializer"}'::jsonb)
ON CONFLICT (tenant_id, pipeline_id) DO UPDATE SET source_id=EXCLUDED.source_id, source_domain=EXCLUDED.source_domain, pipeline_name=EXCLUDED.pipeline_name, description=EXCLUDED.description, status=EXCLUDED.status, stages=EXCLUDED.stages, input_datasets=EXCLUDED.input_datasets, output_topics=EXCLUDED.output_topics, metadata=EXCLUDED.metadata, updated_at=now();
