-- First-class MarketOps asset universe seeded from the Massive Top 50 mega-cap list.

CREATE TABLE IF NOT EXISTS marketops_asset_universe (
  tenant_id text NOT NULL,
  app_id text NOT NULL DEFAULT 'marketops',
  domain text NOT NULL DEFAULT 'market_data',
  use_case text NOT NULL DEFAULT 'daily_market_surveillance',
  source_id text NOT NULL DEFAULT 'src-massive',
  universe_group text NOT NULL,
  rank integer NOT NULL CHECK (rank > 0),
  ticker text NOT NULL,
  ticker_key text NOT NULL,
  company text NOT NULL,
  company_key text NOT NULL,
  asset_type text NOT NULL DEFAULT 'equity',
  exchange text NOT NULL DEFAULT '',
  sector text NOT NULL DEFAULT '',
  sector_key text NOT NULL DEFAULT '',
  industry text NOT NULL DEFAULT '',
  industry_key text NOT NULL DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, universe_group, ticker)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_marketops_asset_universe_rank
  ON marketops_asset_universe (tenant_id, universe_group, rank);

CREATE INDEX IF NOT EXISTS idx_marketops_asset_universe_active
  ON marketops_asset_universe (tenant_id, app_id, domain, use_case, is_active, rank);

INSERT INTO marketops_asset_universe (
  tenant_id, app_id, domain, use_case, source_id, universe_group, rank, ticker, ticker_key,
  company, company_key, asset_type, exchange, sector, sector_key, industry, industry_key, metadata
) VALUES
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 1, 'NVDA', 'nvda', 'NVIDIA', 'nvidia', 'equity', '', 'Technology', 'technology', 'Semiconductors', 'semiconductors', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 2, 'AAPL', 'aapl', 'Apple', 'apple', 'equity', '', 'Technology', 'technology', 'Hardware', 'hardware', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 3, 'GOOGL', 'googl', 'Alphabet', 'alphabet', 'equity', '', 'Technology', 'technology', 'Software', 'software', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 4, 'MSFT', 'msft', 'Microsoft', 'microsoft', 'equity', '', 'Technology', 'technology', 'Software', 'software', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 5, 'AMZN', 'amzn', 'Amazon', 'amazon', 'equity', '', 'Consumer Discretionary', 'consumer_discretionary', 'Retail', 'retail', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 6, 'TSM', 'tsm', 'TSMC', 'tsmc', 'equity', '', 'Technology', 'technology', 'Semiconductors', 'semiconductors', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 7, 'SPCX', 'spcx', 'SpaceX', 'spacex', 'equity', '', 'Aerospace & Defense', 'aerospace_defense', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 8, 'AVGO', 'avgo', 'Broadcom', 'broadcom', 'equity', '', 'Technology', 'technology', 'Semiconductors', 'semiconductors', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 9, '2222.SR', '2222_sr', 'Saudi Aramco', 'saudi_aramco', 'equity', '', 'Energy', 'energy', 'Oil & Gas', 'oil_gas', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 10, 'TSLA', 'tsla', 'Tesla', 'tesla', 'equity', '', 'Automotive', 'automotive', 'Clean Energy', 'clean_energy', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 11, 'META', 'meta', 'Meta Platforms', 'meta_platforms', 'equity', '', 'Interactive Media', 'interactive_media', 'Software', 'software', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 12, '005930.KS', '005930_ks', 'Samsung Electronics', 'samsung_electronics', 'equity', '', 'Technology Hardware', 'technology_hardware', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 13, 'MU', 'mu', 'Micron Technology', 'micron_technology', 'equity', '', 'Technology', 'technology', 'Semiconductors', 'semiconductors', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 14, 'BRK.B', 'brk_b', 'Berkshire Hathaway', 'berkshire_hathaway', 'equity', '', 'Financial Services', 'financial_services', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 15, 'LLY', 'lly', 'Eli Lilly', 'eli_lilly', 'equity', '', 'Healthcare', 'healthcare', 'Pharmaceuticals', 'pharmaceuticals', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 16, '000660.KS', '000660_ks', 'SK Hynix', 'sk_hynix', 'equity', '', 'Technology', 'technology', 'Semiconductors', 'semiconductors', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 17, 'JPM', 'jpm', 'JPMorgan Chase', 'jpmorgan_chase', 'equity', '', 'Financials', 'financials', 'Banking', 'banking', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 18, 'AMD', 'amd', 'AMD', 'amd', 'equity', '', 'Technology', 'technology', 'Semiconductors', 'semiconductors', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 19, 'WMT', 'wmt', 'Walmart', 'walmart', 'equity', '', 'Consumer Staples', 'consumer_staples', 'Retail', 'retail', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 20, 'ASML', 'asml', 'ASML', 'asml', 'equity', '', 'Semiconductor Equipment', 'semiconductor_equipment', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 21, 'V', 'v', 'Visa', 'visa', 'equity', '', 'Financial Services', 'financial_services', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 22, 'JNJ', 'jnj', 'Johnson & Johnson', 'johnson_johnson', 'equity', '', 'Healthcare', 'healthcare', 'Pharmaceuticals', 'pharmaceuticals', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 23, 'INTC', 'intc', 'Intel', 'intel', 'equity', '', 'Technology', 'technology', 'Semiconductors', 'semiconductors', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 24, 'XOM', 'xom', 'Exxon Mobil', 'exxon_mobil', 'equity', '', 'Energy', 'energy', 'Oil & Gas', 'oil_gas', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 25, 'TCEHY', 'tcehy', 'Tencent', 'tencent', 'equity', '', 'Technology', 'technology', 'Internet', 'internet', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 26, 'MA', 'ma', 'Mastercard', 'mastercard', 'equity', '', 'Financial Services', 'financial_services', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 27, 'AMAT', 'amat', 'Applied Materials', 'applied_materials', 'equity', '', 'Semiconductor Equipment', 'semiconductor_equipment', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 28, 'ABBV', 'abbv', 'AbbVie', 'abbvie', 'equity', '', 'Healthcare', 'healthcare', 'Biopharma', 'biopharma', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 29, 'CSCO', 'csco', 'Cisco Systems', 'cisco_systems', 'equity', '', 'Technology', 'technology', 'Networking', 'networking', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 30, 'CAT', 'cat', 'Caterpillar', 'caterpillar', 'equity', '', 'Industrials', 'industrials', 'Machinery', 'machinery', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 31, 'LRCX', 'lrcx', 'Lam Research', 'lam_research', 'equity', '', 'Semiconductor Equipment', 'semiconductor_equipment', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 32, 'BAC', 'bac', 'Bank of America', 'bank_of_america', 'equity', '', 'Financials', 'financials', 'Banking', 'banking', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 33, 'COST', 'cost', 'Costco', 'costco', 'equity', '', 'Consumer Staples', 'consumer_staples', 'Retail', 'retail', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 34, 'ORCL', 'orcl', 'Oracle', 'oracle', 'equity', '', 'Technology', 'technology', 'Software', 'software', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 35, 'GE', 'ge', 'General Electric', 'general_electric', 'equity', '', 'Industrials', 'industrials', 'Aerospace', 'aerospace', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 36, 'UNH', 'unh', 'UnitedHealth Group', 'unitedhealth_group', 'equity', '', 'Healthcare Plans', 'healthcare_plans', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 37, '601939.SS', '601939_ss', 'China Construction Bank', 'china_construction_bank', 'equity', '', 'Financials', 'financials', 'Banking', 'banking', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 38, 'KO', 'ko', 'Coca-Cola', 'coca_cola', 'equity', '', 'Consumer Staples', 'consumer_staples', 'Beverages', 'beverages', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 39, 'MS', 'ms', 'Morgan Stanley', 'morgan_stanley', 'equity', '', 'Financial Services', 'financial_services', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 40, 'HD', 'hd', 'Home Depot', 'home_depot', 'equity', '', 'Consumer Discretionary', 'consumer_discretionary', 'Retail', 'retail', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 41, 'PG', 'pg', 'Procter & Gamble', 'procter_gamble', 'equity', '', 'Consumer Staples', 'consumer_staples', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 42, 'ARM', 'arm', 'Arm Holdings', 'arm_holdings', 'equity', '', 'Technology', 'technology', 'Semiconductor IP', 'semiconductor_ip', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 43, 'HSBC', 'hsbc', 'HSBC', 'hsbc', 'equity', '', 'Financials', 'financials', 'Banking', 'banking', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 44, 'CVX', 'cvx', 'Chevron', 'chevron', 'equity', '', 'Energy', 'energy', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 45, 'RO.SW', 'ro_sw', 'Roche', 'roche', 'equity', '', 'Healthcare', 'healthcare', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 46, 'NFLX', 'nflx', 'Netflix', 'netflix', 'equity', '', 'Communication Services', 'communication_services', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 47, 'PLTR', 'pltr', 'Palantir', 'palantir', 'equity', '', 'Technology', 'technology', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 48, 'MRK', 'mrk', 'Merck & Co.', 'merck_co', 'equity', '', 'Healthcare', 'healthcare', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 49, 'GS', 'gs', 'Goldman Sachs', 'goldman_sachs', 'equity', '', 'Financials', 'financials', '', '', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb),
  ('tenant-local', 'marketops', 'market_data', 'daily_market_surveillance', 'src-massive', 'top50_megacap', 50, 'GEV', 'gev', 'GE Vernova', 'ge_vernova', 'equity', '', 'Energy', 'energy', 'Industrials', 'industrials', '{"seed":"top50megacap.normalized.csv","provider":"massive"}'::jsonb)
ON CONFLICT (tenant_id, universe_group, ticker) DO UPDATE SET
  app_id = EXCLUDED.app_id,
  domain = EXCLUDED.domain,
  use_case = EXCLUDED.use_case,
  source_id = EXCLUDED.source_id,
  rank = EXCLUDED.rank,
  ticker_key = EXCLUDED.ticker_key,
  company = EXCLUDED.company,
  company_key = EXCLUDED.company_key,
  asset_type = EXCLUDED.asset_type,
  exchange = EXCLUDED.exchange,
  sector = EXCLUDED.sector,
  sector_key = EXCLUDED.sector_key,
  industry = EXCLUDED.industry,
  industry_key = EXCLUDED.industry_key,
  is_active = true,
  metadata = EXCLUDED.metadata,
  updated_at = now();
