-- S5 private catalog membership with provider-free central activation request.
CREATE POLICY subscriber_watchlist_memberships_catalog_owner_insert ON subscriber_watchlist_memberships FOR INSERT TO signalops_subscriber_migrator WITH CHECK (tenant_id=current_setting('signalops.tenant_id',true));
CREATE POLICY subscriber_watchlist_audit_catalog_owner_insert ON subscriber_watchlist_audit FOR INSERT TO signalops_subscriber_migrator WITH CHECK (tenant_id=current_setting('signalops.tenant_id',true));
CREATE FUNCTION subscriber_add_private_catalog_membership(p_subject text,p_list_id text,p_global_asset_id text,p_correlation_id text)
RETURNS TABLE (tenant_id text,list_id text,global_asset_id text,added_by_subject text,added_at timestamptz,activation_state text)
LANGUAGE sql VOLATILE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
 WITH target AS (SELECT list_id,tenant_id FROM public.subscriber_watchlists WHERE tenant_id=current_setting('signalops.tenant_id',true) AND list_id=p_list_id AND list_kind='private' AND owner_subject=p_subject),
 asset AS (SELECT asset.global_asset_id,COALESCE(coverage.coverage_state,'not_requested') coverage_state,COALESCE(coverage.execution_mode,'shadow') coverage_mode FROM public.subscriber_global_assets asset LEFT JOIN public.subscriber_global_asset_coverage coverage ON coverage.global_asset_id=asset.global_asset_id AND coverage.coverage_product='eod_baseline' WHERE asset.global_asset_id=p_global_asset_id AND asset.eligibility_status='eligible'),
 inserted AS (INSERT INTO public.subscriber_watchlist_memberships (tenant_id,list_id,global_asset_id,added_by_subject,provenance) SELECT target.tenant_id,target.list_id,asset.global_asset_id,p_subject,jsonb_build_object('schema_version','subscriber.watchlist.v1','surface','subscriber.catalog') FROM target CROSS JOIN asset ON CONFLICT (list_id,global_asset_id) DO NOTHING RETURNING tenant_id,list_id,global_asset_id,added_by_subject,added_at),
 member AS (SELECT * FROM inserted UNION ALL SELECT membership.tenant_id,membership.list_id,membership.global_asset_id,membership.added_by_subject,membership.added_at FROM public.subscriber_watchlist_memberships membership JOIN target ON target.tenant_id=membership.tenant_id AND target.list_id=membership.list_id JOIN asset ON asset.global_asset_id=membership.global_asset_id WHERE NOT EXISTS (SELECT 1 FROM inserted)),
 audit AS (INSERT INTO public.subscriber_watchlist_audit (audit_id,tenant_id,list_id,actor_subject,mutation,global_asset_id,before_value,after_value,correlation_id,occurred_at) SELECT 'sublistaudit-'||md5(p_list_id||p_global_asset_id||clock_timestamp()::text),tenant_id,list_id,p_subject,'add_catalog_asset',global_asset_id,'{}'::jsonb,jsonb_build_object('global_asset_id',global_asset_id),COALESCE(p_correlation_id,''),now() FROM inserted RETURNING audit_id),
 activation AS (INSERT INTO public.subscriber_global_coverage_activation_requests (activation_request_id,global_asset_id,request_key,request_state,request_reason,requester_kind,requester_tenant_id,requester_subject,requester_list_id,policy_version,provenance,requested_at) SELECT 'subactivation-'||md5(asset.global_asset_id||clock_timestamp()::text),asset.global_asset_id,'subscriber-eod-activation-v1:'||asset.global_asset_id,'queued','subscriber_private_list_cold_asset','user_private_list',target.tenant_id,p_subject,target.list_id,'subscriber-eod-activation-v1',jsonb_build_object('surface','subscriber.catalog','correlation_id',COALESCE(p_correlation_id,'')),now() FROM target CROSS JOIN asset WHERE NOT (asset.coverage_state='active' AND asset.coverage_mode='enabled') ON CONFLICT (request_key) DO UPDATE SET updated_at=now() RETURNING request_state)
 SELECT member.tenant_id,member.list_id,member.global_asset_id,member.added_by_subject,member.added_at,COALESCE((SELECT request_state FROM activation),'active') FROM member;
$$;
ALTER FUNCTION subscriber_add_private_catalog_membership(text,text,text,text) OWNER TO signalops_subscriber_migrator;
REVOKE ALL ON FUNCTION subscriber_add_private_catalog_membership(text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION subscriber_add_private_catalog_membership(text,text,text,text) TO signalops_subscriber_gateway;
