DROP TRIGGER IF EXISTS trg_subscriber_global_intraday_shadow_capture_entries_immutable ON subscriber_global_intraday_shadow_capture_entries;
DROP TRIGGER IF EXISTS trg_subscriber_global_intraday_shadow_capture_runs_immutable ON subscriber_global_intraday_shadow_capture_runs;
DROP FUNCTION IF EXISTS subscriber_global_intraday_shadow_capture_immutable_guard();
REVOKE ALL ON subscriber_global_intraday_shadow_capture_runs, subscriber_global_intraday_shadow_capture_entries FROM signalops_subscriber_global_eod;
DROP TABLE IF EXISTS subscriber_global_intraday_shadow_capture_entries;
DROP TABLE IF EXISTS subscriber_global_intraday_shadow_capture_runs;
