REVOKE ALL ON subscriber_global_eod_provider_revision_field_deltas, subscriber_global_eod_provider_revision_observations, subscriber_global_eod_provider_revision_policies FROM signalops_subscriber_global_eod;
DROP TABLE IF EXISTS subscriber_global_eod_provider_revision_field_deltas;
DROP TABLE IF EXISTS subscriber_global_eod_provider_revision_observations;
DROP TABLE IF EXISTS subscriber_global_eod_provider_revision_policies;
