apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app-to-keycloak
  namespace: signalops-identity
  labels:
    app.kubernetes.io/part-of: signalops
    signalops.syncratic.io/plane: identity
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: signalops-app
          podSelector:
            matchLabels:
              app.kubernetes.io/name: signalops-gateway
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
