import { useEffect, useState } from "react";
import { useTenant } from "../auth/session";
import { ErrorState, LoadingState } from "../components/States";
import { useCyberOpsIoTBehaviour, useCyberOpsIoTNetworkConfig, useUpdateCyberOpsIoTNetworkConfig } from "../api/queries";

export function CyberOpsIoTPanel() {
  const tenant=useTenant(); const config=useCyberOpsIoTNetworkConfig(tenant); const behaviour=useCyberOpsIoTBehaviour(tenant); const update=useUpdateCyberOpsIoTNetworkConfig(tenant); const [text,setText]=useState("");
  useEffect(()=>{if(config.data)setText(config.data.network_config.internal_cidrs.join("\n"))},[config.data]);
  if(config.isLoading)return <LoadingState label="Loading IoT settings..."/>;
  if(config.isError)return <ErrorState error={config.error}/>;
  const data=behaviour.data; const save=()=>update.mutate(text.split(/[\n,]/).map(x=>x.trim()).filter(Boolean));
  return <section className="rounded border border-gray-200 bg-white p-3 space-y-3"><div><h2 className="text-sm font-semibold">IoT device behaviour</h2><p className="text-xs text-gray-500">Internal CIDRs establish device identity. The first seven days are a learning period.</p></div><label className="block text-xs font-medium">Internal network CIDRs<textarea value={text} onChange={e=>setText(e.target.value)} rows={3} className="mt-1 w-full rounded border p-2 font-mono text-xs" placeholder="192.168.10.0/24"/></label><button onClick={save} disabled={update.isPending} className="rounded bg-brand-600 px-3 py-1 text-xs text-white disabled:opacity-50">{update.isPending?"Applying...":"Apply CIDRs"}</button>{update.isError?<p className="text-xs text-red-700">Unable to apply CIDRs: {String(update.error)}</p>:null}{update.isSuccess?<p className="text-xs text-emerald-700">CIDRs applied.</p>:null}{behaviour.isLoading?<LoadingState label="Loading IoT device behaviour..."/>:behaviour.isError?<p className="text-xs text-amber-700">Traffic profiles are temporarily unavailable; CIDR settings can still be applied.</p>:!data || !data.internal_cidrs.length?<p className="text-sm text-amber-700">Configure internal CIDRs to identify IoT devices and begin learning communication behaviour.</p>:<><div className="grid gap-2 sm:grid-cols-3"><Metric label="Devices active (24h)" value={data.device_count}/><Metric label="Baseline" value={`${data.baseline_days}-day learning`}/><Metric label="Observed paths" value={data.flows.length}/></div><div><h3 className="text-xs font-semibold">Device communication profiles</h3><p className="text-[11px] text-gray-500">Allowed ingress, egress, and lateral relationships. Behaviour-change signals activate after learning is mature.</p><div className="mt-2 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b text-gray-500"><th>Device</th><th>Peer</th><th>Direction</th><th>Service</th><th>Logs</th><th>Last seen</th></tr></thead><tbody>{data.flows.slice(0,30).map(f=><tr key={`${f.device_ip}-${f.peer_ip}-${f.direction}-${f.protocol}-${f.destination_port}`} className="border-b"><td className="font-mono">{f.device_ip}</td><td className="font-mono">{f.peer_ip}</td><td>{f.direction}</td><td>{f.protocol.toUpperCase()}/{f.destination_port}</td><td>{f.count}</td><td>{new Date(f.last_seen).toLocaleString()}</td></tr>)}</tbody></table></div></div></>}</section>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded border p-2"><div className="text-[11px] text-gray-500">{label}</div><div className="text-sm font-semibold">{value}</div></div>}
