import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../api/client';
import { useTenant } from '../auth/session';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { formatPercent, formatUtc } from '../lib/format';
import type { MarketOpsSignalAssuranceEffectivenessObservation } from '../types';

const pct = (value?: number) => value == null || !Number.isFinite(value) ? "-" : formatPercent(value);
const label = (value: string) => value.replace(/_/g, ' ').replace(/\b\w/g, (letter: string) => letter.toUpperCase());

export function MarketOpsSignalAssuranceDrilldownPanel() {
  const tenantId = useTenant();
  const [source, setSource] = useState('LEGACY');
  const [dimension, setDimension] = useState('direction');
  const [cohort, setCohort] = useState('');
  const [selected, setSelected] = useState<MarketOpsSignalAssuranceEffectivenessObservation | null>(null);
  const cohorts = useQuery({ queryKey: ['saf-drilldown-cohorts', tenantId, source, dimension], queryFn: () => api.getMarketOpsSignalAssuranceEffectiveness(tenantId, source, dimension), staleTime: 30_000 });
  const observations = useQuery({ queryKey: ['saf-drilldown-observations', tenantId, source, dimension, cohort], queryFn: () => api.listMarketOpsSignalAssuranceEffectivenessObservations(tenantId, source, dimension, cohort), enabled: Boolean(cohort), staleTime: 30_000 });
  const opportunity = useQuery({ queryKey: ['saf-drilldown-opportunity', tenantId, selected?.reference_id], queryFn: () => api.getMarketOpsOpportunity(selected?.reference_id || '', tenantId), enabled: selected?.evidence_source === 'LEGACY' && Boolean(selected?.reference_id), staleTime: 30_000 });
  const assertion = useQuery({ queryKey: ['saf-drilldown-assertion', tenantId, selected?.reference_id], queryFn: () => api.getMarketOpsSignalAssuranceAssertion(selected?.reference_id || '', tenantId), enabled: selected?.evidence_source === 'SAF' && Boolean(selected?.reference_id), staleTime: 30_000 });
  const chooseCohort = (value: string) => { setCohort(value); setSelected(null); };
  return <section className="space-y-3 rounded border border-gray-200 bg-white p-3">
    <div><h2 className="text-base font-semibold">Analyst drill-down</h2><p className="max-w-3xl text-xs text-gray-500">Trace any effectiveness cohort to every included terminal observation, then open its immutable source audit. Historical outcomes link to the opportunity and its input signal/evidence identifiers; SAF records link to the assertion, resolved contract, baseline, and provenance.</p></div>
    <div className="flex flex-wrap items-end gap-3 rounded border border-gray-200 bg-gray-50 p-3">
      <label className="text-xs font-medium text-gray-700">Evidence<select value={source} onChange={(event) => { setSource(event.target.value); chooseCohort(''); }} className="mt-1 block rounded border border-gray-300 bg-white px-2 py-1.5 text-sm"><option value="LEGACY">Historical outcomes</option><option value="SAF">SAF validated</option></select></label>
      <label className="text-xs font-medium text-gray-700">Cohort dimension<select value={dimension} onChange={(event) => { setDimension(event.target.value); chooseCohort(''); }} className="mt-1 block rounded border border-gray-300 bg-white px-2 py-1.5 text-sm"><option value="direction">Direction</option><option value="horizon">Horizon</option><option value="confidence_band">Confidence band</option><option value="algorithm_version">Algorithm / version</option><option value="signal_type">Signal type</option></select></label>
    </div>
    {cohorts.isLoading ? <LoadingState label="Loading cohorts..." /> : cohorts.isError ? <ErrorState error={cohorts.error} /> : <div className="overflow-x-auto rounded border border-gray-200"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-3 py-2">Cohort</th><th className="px-3 py-2">Accuracy</th><th className="px-3 py-2">Sample</th><th className="px-3 py-2">Action</th></tr></thead><tbody className="divide-y divide-gray-100">{(cohorts.data?.effectiveness ?? []).map((row) => <tr key={row.dimension_value} className={cohort === row.dimension_value ? 'bg-brand-50' : ''}><td className="px-3 py-2 font-mono text-xs">{row.dimension_value}</td><td className="px-3 py-2">{pct(row.directional_accuracy)}</td><td className="px-3 py-2 text-xs">{row.directional_hits}/{row.sample_size}{row.exploratory ? " - exploratory" : ""}</td><td className="px-3 py-2"><button type="button" onClick={() => chooseCohort(row.dimension_value)} className="text-xs font-medium text-brand-700 underline">Inspect observations</button></td></tr>)}</tbody></table>{(cohorts.data?.effectiveness.length ?? 0) === 0 ? <EmptyState message="No cohorts match this evidence class." /> : null}</div>}
    {cohort ? <section className="space-y-2 rounded border border-brand-200 bg-brand-50 p-3"><div><h3 className="text-sm font-semibold">Included observations: {cohort}</h3><p className="text-xs text-gray-600">Only complete terminal observations that contribute to this effectiveness figure appear here.</p></div>{observations.isLoading ? <LoadingState label="Loading included observations..." /> : observations.isError ? <ErrorState error={observations.error} /> : <div className="overflow-x-auto rounded border border-brand-200 bg-white"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-3 py-2">Signal</th><th className="px-3 py-2">Origin</th><th className="px-3 py-2">Outcome</th><th className="px-3 py-2">Match</th><th className="px-3 py-2">Aligned move</th><th className="px-3 py-2">Action</th></tr></thead><tbody className="divide-y divide-gray-100">{(observations.data?.observations ?? []).map((row) => <tr key={row.observation_id} className={selected?.observation_id === row.observation_id ? 'bg-yellow-50' : ''}><td className="px-3 py-2"><div className="font-mono font-semibold">{row.symbol}</div><div className="text-xs text-gray-500">{label(row.direction)} - {row.horizon_sessions} session{row.horizon_sessions === 1 ? '' : 's'}</div></td><td className="px-3 py-2 text-xs">{row.origin_at ? formatUtc(row.origin_at) : "-"}</td><td className="px-3 py-2 text-xs">{row.outcome_at ? formatUtc(row.outcome_at) : "-"}</td><td className={row.directional_hit ? 'px-3 py-2 text-xs font-semibold text-green-700' : 'px-3 py-2 text-xs font-semibold text-red-700'}>{row.directional_hit ? 'Matched' : 'Missed'}</td><td className="px-3 py-2 text-xs">{pct(row.directional_return)}</td><td className="px-3 py-2"><button type="button" onClick={() => setSelected(row)} className="text-xs font-medium text-brand-700 underline">Inspect audit</button></td></tr>)}</tbody></table>{(observations.data?.observations.length ?? 0) === 0 ? <EmptyState message="No included observations in this cohort." /> : null}</div>}</section> : null}
    {selected ? <section role="dialog" aria-modal="true" className="fixed inset-x-2 bottom-2 z-50 max-h-[80vh] overflow-y-auto space-y-2 rounded border border-gray-300 bg-gray-50 p-3 shadow-xl sm:static sm:max-h-none sm:overflow-visible sm:shadow-none"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">Observation audit: {selected.symbol}</h3><p className="text-xs text-gray-600">{selected.evidence_source === 'SAF' ? 'Confirmed SAF assertion audit.' : 'Historical opportunity outcome audit; not an SAF assertion.'}</p></div><button type="button" onClick={() => setSelected(null)} className="rounded border border-gray-300 bg-white px-2 py-1 text-xs font-medium text-gray-700">Close</button></div><dl className="grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-gray-500">Signal score</dt><dd className="font-medium">{pct(selected.signal_score)}</dd></div><div><dt className="text-gray-500">Confidence</dt><dd className="font-medium">{pct(selected.confidence)}</dd></div><div><dt className="text-gray-500">Raw return</dt><dd className="font-medium">{pct(selected.absolute_return)}</dd></div><div><dt className="text-gray-500">Calculation</dt><dd className="font-mono">{selected.calculation_version || "-"}</dd></div></dl><details open><summary className="cursor-pointer text-xs font-medium text-brand-700">Observation record</summary><pre className="mt-2 max-h-64 overflow-auto rounded bg-white p-2 text-[10px] text-gray-700">{JSON.stringify(selected, null, 2)}</pre></details>{selected.evidence_source === 'LEGACY' ? opportunity.isLoading ? <LoadingState label="Loading opportunity provenance..." /> : opportunity.isError ? <ErrorState error={opportunity.error} /> : <details open><summary className="cursor-pointer text-xs font-medium text-brand-700">Opportunity provenance and source identifiers</summary><pre className="mt-2 max-h-80 overflow-auto rounded bg-white p-2 text-[10px] text-gray-700">{JSON.stringify(opportunity.data?.opportunity, null, 2)}</pre></details> : assertion.isLoading ? <LoadingState label="Loading assertion audit..." /> : assertion.isError ? <ErrorState error={assertion.error} /> : <details open><summary className="cursor-pointer text-xs font-medium text-brand-700">Assertion baseline, provenance, and validation contract</summary><pre className="mt-2 max-h-80 overflow-auto rounded bg-white p-2 text-[10px] text-gray-700">{JSON.stringify(assertion.data?.assertion, null, 2)}</pre></details>}</section> : null}
  </section>;
}

