import { Fragment, useMemo, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ClipboardList, ExternalLink } from 'lucide-react';
import { useAlerts, useMarketOpsOpportunities, useMarketOpsSignalOverview } from '../api/queries';
import { useQuery } from '@tanstack/react-query';
import { api } from '../api/client';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { formatUtc } from '../lib/format';
import { useTenant } from '../auth/session';

type Source = 'opportunity' | 'alert' | 'reversal' | 'options_flow' | 'risk_reward';
type QueueSortKey = 'asset' | 'assessment' | 'priority' | 'evidence' | 'freshness';
type QueueItem = { symbol: string; priority: number; sources: Source[]; title: string; why: string; direction: string; freshness: string; caveats: string[]; links: { label: string; to: string }[] };
const labels: Record<Source, string> = { opportunity: 'Opportunity', alert: 'DSM alert', reversal: 'Exhaustive Reversal', options_flow: 'Options flow', risk_reward: 'Risk/Reward' };

export function MarketOpsReviewQueueRoute() {
  const tenantId = useTenant();
  const [symbol, setSymbol] = useState('');
  const [source, setSource] = useState<Source | ''>('');
  const [selected, setSelected] = useState<string | null>(null);
  const [sort, setSort] = useState<{ key: QueueSortKey; asc: boolean }>({ key: 'priority', asc: false });
  const opportunities = useMarketOpsOpportunities({ tenant_id: tenantId, lifecycle_status: 'active', limit: 200 });
  const alerts = useAlerts({ tenant_id: tenantId, app_id: 'marketops', domain: 'market_data', use_case: 'daily_market_surveillance', status: 'open', limit: 200 });
  const overview = useMarketOpsSignalOverview(tenantId, 'all_active', '10_trade_days');
  const eroc = useQuery({ queryKey: ['marketops-eroc', tenantId], queryFn: () => api.getMarketOpsEROC(tenantId), refetchInterval: 15000 });
  const items = useMemo(() => buildItems(opportunities.data?.opportunities ?? [], alerts.data?.alerts ?? [], eroc.data?.results ?? [], overview.data), [opportunities.data, alerts.data, eroc.data, overview.data]);
  const filtered = items.filter(item => (!symbol || item.symbol.includes(symbol.trim().toUpperCase())) && (!source || item.sources.includes(source))).sort((a, b) => { const value = (item: QueueItem) => sort.key === "asset" ? item.symbol : sort.key === "priority" ? item.priority : sort.key === "assessment" ? item.title : sort.key === "evidence" ? item.sources.length : item.freshness; const left = value(a), right = value(b); const compared = typeof left === "number" && typeof right === "number" ? left - right : String(left).localeCompare(String(right)); return sort.asc ? compared : -compared; });
  const loading = opportunities.isLoading || alerts.isLoading || eroc.isLoading || overview.isLoading;
  const failed = opportunities.isError || alerts.isError || eroc.isError || overview.isError;
  return <div className="space-y-3">
    <div className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="flex items-center gap-1 text-lg font-semibold"><ClipboardList size={18} className="text-brand-700" /> Review Queue</h1><p className="text-xs text-gray-500">Prioritized MarketOps research items. Evidence is grouped by asset, not repeated as raw records.</p></div><div className="text-xs text-gray-500">{filtered.length} material item{filtered.length === 1 ? '' : 's'}</div></div>
    <div className="flex flex-wrap gap-2 rounded border border-gray-200 bg-gray-50 p-3"><input value={symbol} onChange={e => setSymbol(e.target.value)} placeholder="Ticker" aria-label="Filter review queue by ticker" className="w-28 rounded border border-gray-300 bg-white px-2 py-1 text-sm" /><select value={source} onChange={e => setSource(e.target.value as Source | '')} aria-label="Filter review queue by source" className="rounded border border-gray-300 bg-white px-2 py-1 text-sm"><option value="">All evidence</option>{(Object.keys(labels) as Source[]).map(key => <option key={key} value={key}>{labels[key]}</option>)}</select>{(symbol || source) && <button type="button" onClick={() => { setSymbol(''); setSource(''); }} className="rounded border border-gray-300 bg-white px-2 py-1 text-xs text-gray-700 hover:bg-yellow-50">Clear filters</button>}</div>
    {loading ? <LoadingState /> : failed ? <ErrorState error={opportunities.error || alerts.error || eroc.error || overview.error} /> : filtered.length ? <div className="overflow-x-auto rounded border border-gray-200 bg-white"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr>{([['Asset','asset'],['Review assessment','assessment'],['Priority','priority'],['Evidence','evidence'],['Last evidence','freshness']] as [string, QueueSortKey][]).map(([label, key]) => <th key={key} className="px-3 py-2"><button type="button" onClick={() => setSort(current => current.key === key ? { key, asc: !current.asc } : { key, asc: key === 'asset' })} className="inline-flex items-center gap-1 whitespace-nowrap hover:text-yellow-400">{label}<span className={sort.key === key ? 'text-brand-700' : 'text-gray-300'}>{sort.key === key ? sort.asc ? '↑' : '↓' : '↕'}</span></button></th>)}</tr></thead><tbody className="divide-y divide-gray-100">{filtered.map(item => <QueueRow key={item.symbol} item={item} selected={selected === item.symbol} onSelect={() => setSelected(selected === item.symbol ? null : item.symbol)} />)}</tbody></table></div> : <EmptyState message="No material research items match the current filters." />}
  </div>;
}

function buildItems(opportunities: any[], alerts: any[], eroc: any[], overview: any): QueueItem[] {
  const flow = overview?.options_flow_extremes;
  const latestRiskReward = overview?.risk_reward?.points?.[overview.risk_reward.points.length - 1];
  const bySymbol = new Map<string, QueueItem>();
  const add = (symbol: string, source: Source, priority: number, title: string, why: string, direction: string, freshness: string, caveat: string, link: { label: string; to: string }) => {
    if (!symbol) return; const key = symbol.toUpperCase(); const item = bySymbol.get(key) ?? { symbol: key, priority: 0, sources: [], title, why, direction, freshness, caveats: [], links: [{ label: 'Asset detail', to: '/marketops/assets' }] }; const isHighestPriority = priority >= item.priority;
    item.priority = Math.max(item.priority, priority); if (!item.sources.includes(source)) item.sources.push(source); if (isHighestPriority) { item.title = title; item.why = why; item.direction = direction; item.freshness = freshness; }
if (caveat && !item.caveats.includes(caveat)) item.caveats.push(caveat); if (!item.links.some(x => x.to === link.to)) item.links.push(link); bySymbol.set(key, item);
  };
  opportunities.forEach(o => add(o.symbol, 'opportunity', Math.round((o.opportunity_score ?? 0) * 10), 'Active research opportunity', o.summary || 'Compatible research evidence merits analyst review.', o.direction || 'non-directional', o.last_evaluated_date || o.updated_at, o.conflict_score > 0 ? `Conflicting evidence: ${Number(o.conflict_score).toFixed(1)}` : 'Research-only; not a trade instruction.', { label: 'Opportunity evidence', to: `/marketops/opportunities?opportunity_id=${encodeURIComponent(o.opportunity_id)}` }));
  alerts.filter(a => a.severity === 'high' || a.severity === 'critical').forEach(a => { const symbol = entitySymbol(a.entities) || ''; add(symbol, 'alert', a.severity === 'critical' ? 90 : 75, a.title || 'Material DSM alert', a.summary || 'A MarketOps detector produced material evidence.', 'review', a.last_observed_at || a.updated_at, 'Detector evidence requires analyst interpretation; it is not a forecast.', { label: 'Raw alert', to: '/admin/alerts' }); });
  eroc.filter((r: any) => r.trace?.reversal_candidate).forEach((r: any) => add(r.ticker, 'reversal', Math.round(Math.abs(Number(r.trace?.stance_score ?? r.score ?? 0))), 'Exhaustive Reversal review', `${r.trace?.regime === 'climactic_extension' ? 'Climactic extension' : 'Fading price drift'} warrants reversal review.`, String(r.trace?.direction ?? 'review').toLowerCase(), r.trade_date, r.trace?.evidence_complete ? 'Complete evidence; a score prioritizes review, not a prediction.' : 'Evidence is incomplete; use as monitor context.', { label: 'Exhaustive Reversal', to: '/marketops/eroc' }));
  (latestRiskReward?.categories ?? []).filter((category: any) => category.key === "bullish" || category.key === "bearish").forEach((category: any) => category.members?.forEach((member: any) => add(member.ticker, "risk_reward", 70, category.key === "bullish" ? "Bullish Risk/Reward extreme" : "Bearish Risk/Reward extreme", member.label || "Persisted EOD technical posture merits review.", category.key + " technical posture", member.as_of || latestRiskReward.trade_date, "Technical posture is evidence, not a recommendation.", { label: "Risk/Reward evidence", to: "/marketops/assets" })));
  (flow?.categories ?? []).forEach((category: any) => category.members?.forEach((member: any) => add(member.ticker, 'options_flow', 65, category.key === 'call_volume_extreme' ? 'Call-volume extreme' : 'Put-volume extreme', member.label || 'Unusual aggregate options participation.', category.key === 'call_volume_extreme' ? 'bullish flow context' : 'bearish flow context', member.as_of || flow.as_of, 'Aggregate options volume does not establish whether contracts were bought or sold.', { label: 'Asset options context', to: '/marketops/assets' })));
  return [...bySymbol.values()].sort((a, b) => b.priority - a.priority || b.sources.length - a.sources.length || a.symbol.localeCompare(b.symbol));
}
function entitySymbol(value: unknown) { if (!Array.isArray(value)) return ''; const first = value.find((x: any) => typeof x?.symbol === 'string' || typeof x?.ticker === 'string'); return String(first?.symbol ?? first?.ticker ?? ''); }
function QueueRow({ item, selected, onSelect }: { item: QueueItem; selected: boolean; onSelect: () => void }) { return <Fragment><tr onClick={onSelect} className={selected ? "cursor-pointer bg-brand-50" : "cursor-pointer hover:bg-gray-50"}><td className="px-3 py-2 font-mono text-xs font-semibold"><Link to="/marketops/state" search={{ symbol: item.symbol }} onClick={event => event.stopPropagation()} className="text-brand-700 underline hover:text-brand-800" title="Open Market State">{item.symbol}</Link></td><td className="max-w-sm px-3 py-2"><div className="text-xs font-medium text-gray-800">{item.title}</div><div className="truncate text-xs text-gray-500" title={item.why}>{item.direction}</div></td><td className="px-3 py-2 text-xs font-semibold">{item.priority}</td><td className="px-3 py-2">{item.sources.map(source => <span key={source} className="mr-1 inline-flex rounded border border-brand-100 bg-brand-50 px-1.5 py-0.5 text-[11px] text-brand-700">{labels[source]}</span>)}</td><td className="whitespace-nowrap px-3 py-2 text-xs text-gray-600">{formatUtc(item.freshness)}</td></tr>{selected ? <tr className="bg-brand-50"><td colSpan={5} className="p-3"><QueueDetail item={item} /></td></tr> : null}</Fragment>; }
function EvidenceSummary({ source }: { source: Source }) { const text: Record<Source, string> = { opportunity: "Compatible hypothesis evidence and opportunity scoring are active.", alert: "A high or critical DSM detector condition is currently open.", reversal: "A fading or climactic extension met the reversal-review gate.", options_flow: "Aggregate put/call volume crossed the configured extreme threshold.", risk_reward: "Latest persisted EOD Risk/Reward posture is at a bullish or bearish extreme." }; return <li>{text[source]}</li>; }
function QueueDetail({ item }: { item: QueueItem }) { return <div className="rounded border border-brand-200 bg-brand-50 p-3"><div className="text-sm font-semibold">{item.symbol} · analyst context</div><div className="mt-2 grid gap-3 md:grid-cols-2"><div className="md:col-span-2 rounded border border-brand-100 bg-white p-2"><div className="text-xs font-medium text-gray-600">Evidence behind this review</div><ul className="mt-1 list-disc pl-4 text-xs text-gray-700">{item.sources.map(source => <EvidenceSummary key={source} source={source} />)}</ul></div><div><div className="text-xs font-medium text-gray-600">Why review</div><p className="mt-1 text-sm text-gray-800">{item.why}</p><div className="mt-2 text-xs text-gray-500">Direction/context: {item.direction} · Last evidence: {formatUtc(item.freshness)}</div></div><div><div className="text-xs font-medium text-gray-600">Caveats</div><ul className="mt-1 list-disc pl-4 text-xs text-gray-700">{item.caveats.map(c => <li key={c}>{c}</li>)}</ul><div className="mt-3 flex flex-wrap gap-2"><Link to="/marketops/state" search={{ symbol: item.symbol }} onClick={event => event.stopPropagation()} className="inline-flex items-center gap-1 rounded border border-gray-300 bg-white px-2 py-1 text-xs text-brand-700 hover:bg-yellow-50">Market State<ExternalLink size={12} /></Link>{item.links.map(link => <Link key={link.label} to={link.to} className="inline-flex items-center gap-1 rounded border border-gray-300 bg-white px-2 py-1 text-xs text-brand-700 hover:bg-yellow-50">{link.label}<ExternalLink size={12} /></Link>)}</div></div></div><p className="mt-3 text-[11px] text-gray-500">Research-only. Use the linked technical audit ledgers for raw signals, alerts, artifacts, and full provenance.</p></div>; }
