import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from '@tanstack/react-router';
import { api } from '../api/client';
import { ErrorState, LoadingState, EmptyState } from '../components/States';
import type { MarketOpsValuationRow } from '../types';
import { sortableTableHeaderButtonClass } from '../components/SortableTableHeader';
import { useTenant } from "../auth/session";
import { MarketOpsWatchlistSelector } from "../components/MarketOpsWatchlistContext";

const classificationTone: Record<string, string> = { exceptional: 'text-green-700', opportunity: 'text-green-700', neutral: 'text-gray-700', weak: 'text-amber-700', avoid: 'text-red-700' };
type ValuationSortKey = 'asset' | 'dosm' | 'vc' | 'posture' | 'confidence' | 'asOf';
type SortDirection = 'asc' | 'desc';

function strategicDosm(row: MarketOpsValuationRow) { return row.dosm?.score; }
function tacticalOverlay(row: MarketOpsValuationRow) { return row.tactical?.overlay; }
function classificationFor(row: MarketOpsValuationRow) { return row.dosm?.classification ?? row.vc?.classification ?? 'unavailable'; }
function revenueGrowth(row: MarketOpsValuationRow) { const trace = row.vc?.trace ?? row.dosm?.trace; const cagr = trace?.raw_metrics?.revenue_cagr_3y_annual; const score = trace?.component_scores?.revenue_growth_score; return typeof cagr === 'number' && typeof score === 'number' ? { cagr, score } : undefined; }
function sortValue(row: MarketOpsValuationRow, key: ValuationSortKey): string | number | undefined { switch (key) { case 'asset': return row.ticker; case 'dosm': return strategicDosm(row); case 'vc': return row.vc?.score; case 'posture': return tacticalOverlay(row); case 'confidence': return row.confidence; case 'asOf': return row.trade_date; } }
export function sortMarketOpsValuationRows(rows: MarketOpsValuationRow[], key: ValuationSortKey, direction: SortDirection) { const multiplier = direction === 'asc' ? 1 : -1; return rows.map((row, index) => ({ row, index })).sort((left, right) => { const a = sortValue(left.row, key); const b = sortValue(right.row, key); if (a == null) return b == null ? left.index - right.index : 1; if (b == null) return -1; const comparison = typeof a === 'number' && typeof b === 'number' ? a - b : String(a).localeCompare(String(b), undefined, { sensitivity: 'base', numeric: true }); return comparison === 0 ? left.index - right.index : comparison * multiplier; }).map(({ row }) => row); }

export function MarketOpsValuationRoute() {
  const tenantId = useTenant();
  const [selected, setSelected] = useState<string | null>(null);
  const [eligibleOnly, setEligibleOnly] = useState(true);
  const [tickerFilter, setTickerFilter] = useState('');
  const [classificationFilter, setClassificationFilter] = useState('');
  const [minimumDosm, setMinimumDosm] = useState('');
  const [minimumConfidence, setMinimumConfidence] = useState('');
  const [sort, setSort] = useState<{ key: ValuationSortKey; direction: SortDirection } | null>(null);
  const query = useQuery({ queryKey: ["marketops-valuation", tenantId, eligibleOnly], queryFn: () => api.getMarketOpsValuation(tenantId, eligibleOnly), staleTime: 5 * 60_000, refetchOnMount: 'always' });
  const rows = query.data?.results ?? [];
  const classifications = useMemo(() => Array.from(new Set(rows.map(classificationFor))).sort(), [rows]);
  const filteredRows = useMemo(() => rows.filter(row => {
    const classification = classificationFor(row);
    const dosm = strategicDosm(row) ?? -Infinity;
    return (!tickerFilter || row.ticker.toLowerCase().includes(tickerFilter.toLowerCase()))
      && (!classificationFilter || classification === classificationFilter)
      && (!minimumDosm || dosm >= Number(minimumDosm))
      && (!minimumConfidence || row.confidence >= Number(minimumConfidence));
  }), [rows, tickerFilter, classificationFilter, minimumDosm, minimumConfidence]);
  const displayedRows = useMemo(() => sort ? sortMarketOpsValuationRows(filteredRows, sort.key, sort.direction) : filteredRows, [filteredRows, sort]);
  const toggleSort = (key: ValuationSortKey) => setSort(current => current?.key === key ? { key, direction: current.direction === 'asc' ? 'desc' : 'asc' } : { key, direction: 'asc' });
  return <div className="space-y-3">
    <div className="flex flex-wrap items-start justify-between gap-2"><div><h1 className="text-lg font-semibold">Valuation & DOSM</h1><p className="text-xs text-gray-500">Weekly deterministic valuation research. FMP supplies annual financials; Massive supplies the canonical close. This is not a recommendation.</p><p className="mt-1 text-xs text-brand-700">Annual profile: three-year revenue CAGR and its 0–10 growth score are shown together when four annual statements and a canonical close are available.</p><div className="mt-2 max-w-3xl space-y-1 text-xs text-gray-600"><p><span className="font-semibold text-gray-800">Valuation Composite (VC):</span> a relative valuation score from P/S, GAAP P/E, EV/EBITDA, and peer context—an explainable valuation anchor, not a price target.</p><p><span className="font-semibold text-gray-800">Distressed Opportunity Scoring Model (DOSM):</span> combines VC with operating quality, cash generation, balance-sheet strength, and a bounded technical adjustment to prioritize deeper research.</p></div></div><div className="flex items-center gap-3"><MarketOpsWatchlistSelector /><label className="inline-flex items-center gap-2 text-xs text-gray-600"><input type="checkbox" checked={eligibleOnly} onChange={(event) => setEligibleOnly(event.target.checked)} /> Eligible only</label></div></div>
    {query.isLoading ? <LoadingState label="Loading valuation results..." /> : query.isError ? <ErrorState error={query.error} /> : !rows.length ? <EmptyState message="No Valuation or DOSM result is available yet. Run the weekly Friday valuation job after the close." /> : <>
      <div className="flex flex-wrap items-end gap-2 rounded border border-gray-200 bg-gray-50 p-2 text-xs"><label className="text-gray-600">Ticker<input value={tickerFilter} onChange={event => setTickerFilter(event.target.value)} placeholder="Search" className="mt-1 block w-28 rounded border border-gray-300 bg-white px-2 py-1 text-xs" /></label><label className="text-gray-600">Classification<select value={classificationFilter} onChange={event => setClassificationFilter(event.target.value)} className="mt-1 block rounded border border-gray-300 bg-white px-2 py-1 text-xs"><option value="">All</option>{classifications.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label className="text-gray-600">Min DOSM<input type="number" min="0" max="10" step="0.1" value={minimumDosm} onChange={event => setMinimumDosm(event.target.value)} className="mt-1 block w-20 rounded border border-gray-300 bg-white px-2 py-1 text-xs" /></label><label className="text-gray-600">Min confidence<input type="number" min="0" max="100" step="1" value={minimumConfidence} onChange={event => setMinimumConfidence(event.target.value)} className="mt-1 block w-20 rounded border border-gray-300 bg-white px-2 py-1 text-xs" /></label><button type="button" onClick={() => { setTickerFilter(''); setClassificationFilter(''); setMinimumDosm(''); setMinimumConfidence(''); }} className="rounded border border-gray-300 bg-white px-2 py-1 text-xs text-gray-600 hover:bg-gray-100">Clear filters</button><span className="ml-auto text-gray-600">{displayedRows.length} of {rows.length} assets</span></div>
      <div className="overflow-x-auto rounded border border-gray-200 bg-white"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><SortableValuationHeader label="Asset" sortKey="asset" activeSort={sort} onSort={toggleSort} /><SortableValuationHeader label="Strategic DOSM" sortKey="dosm" activeSort={sort} onSort={toggleSort} /><SortableValuationHeader label="Strategic VC" sortKey="vc" activeSort={sort} onSort={toggleSort} /><th className="px-3 py-2">Revenue growth · 3Y CAGR</th><SortableValuationHeader label="Tactical posture" sortKey="posture" activeSort={sort} onSort={toggleSort} /><SortableValuationHeader label="Confidence" sortKey="confidence" activeSort={sort} onSort={toggleSort} /><SortableValuationHeader label="As of" sortKey="asOf" activeSort={sort} onSort={toggleSort} /></tr></thead><tbody className="divide-y divide-gray-100">{displayedRows.map(row => <ValuationRows key={`${row.ticker}-${row.trade_date}`} row={row} selected={selected === row.ticker} onSelect={() => setSelected(selected === row.ticker ? null : row.ticker)} />)}</tbody></table></div>
    </>}
  </div>;
}
function SortableValuationHeader({ label, sortKey, activeSort, onSort }: { label: string; sortKey: ValuationSortKey; activeSort: { key: ValuationSortKey; direction: SortDirection } | null; onSort: (key: ValuationSortKey) => void }) { const active = activeSort?.key === sortKey; const ascending = activeSort?.direction === 'asc'; return <th className="px-3 py-2" aria-sort={active ? (ascending ? 'ascending' : 'descending') : 'none'}><button type="button" onClick={() => onSort(sortKey)} className={sortableTableHeaderButtonClass} aria-label={'Sort by ' + label}>{label}<span aria-hidden="true" className={active ? 'text-brand-700' : 'text-gray-300'}>{active ? (ascending ? '↑' : '↓') : '↕'}</span></button></th>; }
function ValuationRows({ row, selected, onSelect }: { row: MarketOpsValuationRow; selected: boolean; onSelect: () => void }) { const classification = classificationFor(row); const growth = revenueGrowth(row); return <><tr onClick={onSelect} className={selected ? 'cursor-pointer bg-brand-50' : 'cursor-pointer hover:bg-gray-50'}><td className="px-3 py-2 font-mono text-xs font-semibold"><Link to="/marketops/state" search={{ symbol: row.ticker }} onClick={event => event.stopPropagation()} className="text-brand-700 underline hover:text-brand-800" title="Open Market State">{row.ticker}</Link>{row.data_profile === 'ttm_only' ? <span className="ml-1 rounded bg-amber-100 px-1 py-0.5 text-[10px] font-sans font-medium text-amber-800">TTM</span> : null}</td><td className="px-3 py-2"><span className="font-medium">{strategicDosm(row)?.toFixed(2) ?? '—'}</span><span className={'ml-1 text-xs ' + (classificationTone[classification] ?? 'text-gray-700')}>{classification}</span></td><td className="px-3 py-2">{row.vc?.score.toFixed(2) ?? '—'}</td><td className="px-3 py-2 text-xs">{growth ? <><span className="font-medium">{(growth.cagr * 100).toFixed(1)}%</span><span className="text-gray-500"> · {growth.score.toFixed(2)}/10</span></> : <span className="text-gray-500">Unavailable</span>}</td><td className="px-3 py-2"><PostureBadge tactical={row.tactical} /></td><td className="px-3 py-2 text-xs">{row.confidence}% · {row.confidence_label}</td><td className="px-3 py-2 text-xs text-gray-600">{row.trade_date}</td></tr>{selected ? <tr className="bg-brand-50"><td colSpan={7} className="p-3"><ValuationTrace row={row} onClose={onSelect} /></td></tr> : null}</>; }
function PostureBadge({ tactical }: { tactical?: MarketOpsValuationRow['tactical'] }) { if (!tactical) return <span className="text-xs text-gray-500">Unavailable</span>; const tone = tactical.posture === 'constructive' ? 'border-green-200 bg-green-50 text-green-700' : tactical.posture === 'caution' ? 'border-amber-200 bg-amber-50 text-amber-700' : 'border-gray-200 bg-gray-50 text-gray-700'; const delta = tactical.overlay >= 0 ? '+' : ''; return <span className={'inline-flex rounded border px-1.5 py-0.5 text-xs font-medium ' + tone}>{tactical.posture} · {delta}{tactical.overlay.toFixed(1)}</span>; }
function ValuationTrace({ row, onClose }: { row: MarketOpsValuationRow; onClose: () => void }) { const trace=row.dosm?.trace ?? row.vc?.trace; const ttm=trace?.data_profile === 'ttm_only'; return <div className="rounded border border-brand-200 bg-brand-50 p-3"><div className="flex items-start justify-between gap-2"><div><h2 className="text-sm font-semibold">{row.ticker} calculation trace</h2><p className="text-xs text-gray-600">{row.model_version} · {row.evaluation_status} · immutable weekly result</p>{ttm ? <p className="mt-1 text-xs text-amber-800">TTM-only: the growth score and high-valuation/low-growth penalty were not calculated.</p> : null}</div><button type="button" onClick={event => { event.stopPropagation(); onClose(); }} className="text-xs text-brand-700 underline">Close</button></div><div className="mt-3 grid gap-3 lg:grid-cols-2"><div className="rounded border border-brand-100 bg-white p-2 text-xs text-gray-600"><div className="font-semibold text-brand-800">Valuation Composite algorithm</div><p className="mt-1">P/S (40%), GAAP P/E (30%), and EV/EBITDA (30%) form the base. The peer adjustment applies once. {ttm ? 'The CAGR-dependent penalty is withheld.' : 'The high-valuation/low-growth penalty applies once.'} VC fair value = price × exp(0.1 × (VC − 5)).</p></div><div className="rounded border border-brand-100 bg-white p-2 text-xs text-gray-600"><div className="font-semibold text-brand-800">DOSM algorithm</div><p className="mt-1">Strategic DOSM combines final VC (50%), fundamental quality (50%), and its weekly bounded RSI/SMA technical adjustment. Daily Tactical Posture is separate current-condition context; it does not change either strategic score. {ttm ? 'The five available TTM-derived fundamental dimensions are reweighted equally.' : 'It includes the revenue-growth dimension.'} It does not repeat peer or growth penalties. DOSM fair value = price × exp(0.1 × (DOSM − 5)).</p></div></div><div className="mt-3 grid gap-3 lg:grid-cols-3"><TacticalPostureTrace tactical={row.tactical} /><TraceGroup title="Raw metrics" values={trace?.raw_metrics} /><TraceGroup title="Component scores" values={trace?.component_scores} /><div className="rounded border border-brand-100 bg-white p-2 text-xs"><div className="font-semibold text-brand-800">Confidence</div><div className="mt-1">{trace?.confidence ?? row.confidence}% · {trace?.confidence_label ?? row.confidence_label}</div><ul className="mt-1 list-disc pl-4 text-gray-600">{(trace?.confidence_reasons ?? []).map((reason: string) => <li key={reason}>{reason}</li>)}</ul><p className="mt-2 text-[11px] text-gray-500">EBITDA is sourced from FMP and retained in the calculation provenance.</p></div></div></div> }
function TacticalPostureTrace({ tactical }: { tactical?: MarketOpsValuationRow['tactical'] }) { return <div className="rounded border border-brand-100 bg-white p-2 text-xs"><div className="font-semibold text-brand-800">Daily Tactical Posture</div>{tactical ? <><div className="mt-1"><PostureBadge tactical={tactical} /></div><p className="mt-1 text-gray-600">Derived after EOD from RSI reversal, SMA trend, and five-day price extension. It is not a second valuation score.</p><TraceGroup title="Technical components" values={tactical.technical_components} /></> : <p className="mt-1 text-gray-500">Unavailable until all required daily technical features are usable.</p>}</div>; }
function TraceGroup({ title, values }: { title: string; values?: Record<string, number> }) { return <div className="rounded border border-brand-100 bg-white p-2 text-xs"><div className="mb-1 font-semibold text-brand-800">{title}</div>{values && Object.keys(values).length ? <dl className="space-y-1">{Object.entries(values).map(([key,value]) => <div key={key} className="flex justify-between gap-2"><dt className="text-gray-600">{key.replace(/_/g, ' ')}</dt><dd className="font-mono">{typeof value === 'number' ? value.toFixed(4) : String(value)}</dd></div>)}</dl> : <span className="text-gray-500">Unavailable</span>}</div> }
