import { Fragment, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { api } from "../api/client";
import { Link } from '@tanstack/react-router';
import { MarketOpsPriceSentimentChart } from "./MarketOpsAssetsRoute";

type CandidateFilter = "all" | "complete" | "incomplete" | "fading_drift" | "climactic_extension" | "trend_supported";
type CandidateSort = "assessment" | "asset" | "extension" | "participation" | "flow";

const number = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value : 0;
const fixed = (value: unknown, decimals = 1) => typeof value === "number" && Number.isFinite(value) ? value.toFixed(decimals) : "—";
const title = (value: unknown) => String(value ?? "").replace(/_/g, " ");
const directionLabel = (trace: any) => trace.direction === "BULLISH" ? "Bullish reversal" : trace.direction === "BEARISH" ? "Bearish reversal" : "No reversal stance";
const regimeLabel = (regime: unknown) => ({ fading_drift: "Fading drift", climactic_extension: "Climactic extension", trend_supported: "Trend-supported", unresolved: "Unresolved" }[String(regime)] ?? "Unresolved");
const candidateValue = (row: any, key: CandidateSort) => {
  const trace = row.trace ?? {};
  if (key === "asset") return row.ticker;
  if (key === "assessment") return Math.abs(number(trace.stance_score));
  if (key === "extension") return number(trace.price_extension_units);
  if (key === "participation") return trace.regime === "climactic_extension" ? number(trace.relative_volume_20d) : 1 - number(trace.volume_ratio);
  return number(trace.reversal_flow_ratio);
};

export function MarketOpsEROCRoute() {
  const [selected, setSelected] = useState<string | null>(null);
  const [tickerFilter, setTickerFilter] = useState("");
  const [candidateFilter, setCandidateFilter] = useState<CandidateFilter>("all");
  const [sort, setSort] = useState<{ key: CandidateSort; asc: boolean }>({ key: "assessment", asc: false });
  const q = useQuery({ queryKey: ["marketops-eroc", "tenant-local"], queryFn: () => api.getMarketOpsEROC("tenant-local"), refetchInterval: 5 * 60 * 1000 });
  const { candidates, monitor } = useMemo(() => {
    const term = tickerFilter.trim().toUpperCase();
    const all = (q.data?.results ?? []).filter((row: any) => !term || String(row.ticker ?? "").toUpperCase().includes(term));
    const candidateRows = all.filter((row: any) => row.trace?.reversal_candidate || row.trace?.regime === "trend_supported").filter((row: any) => candidateFilter === "all" || candidateFilter === "complete" && row.trace?.evidence_complete || candidateFilter === "incomplete" && !row.trace?.evidence_complete || row.trace?.regime === candidateFilter).sort((left: any, right: any) => {
      const reversal = Number(Boolean(right.trace?.reversal_candidate)) - Number(Boolean(left.trace?.reversal_candidate));
      if (reversal !== 0) return reversal;
      const complete = Number(Boolean(right.trace?.evidence_complete)) - Number(Boolean(left.trace?.evidence_complete));
      if (complete !== 0) return complete;
      const a = candidateValue(left, sort.key), b = candidateValue(right, sort.key);
      const compared = typeof a === "number" ? a - Number(b) : String(a).localeCompare(String(b));
      return sort.asc ? compared : -compared;
    });
    return { candidates: candidateRows, monitor: all.filter((row: any) => !row.trace?.reversal_candidate && row.trace?.regime !== "trend_supported").sort((a: any, b: any) => String(a.ticker).localeCompare(String(b.ticker))) };
  }, [q.data, tickerFilter, candidateFilter, sort]);
  const toggleSort = (key: CandidateSort) => setSort(current => current.key === key ? { key, asc: !current.asc } : { key, asc: key === "asset" });
  const clear = () => { setTickerFilter(""); setCandidateFilter("all"); };
  const active = tickerFilter || candidateFilter !== "all";
  return <div className="space-y-3">
    <div><h1 className="text-lg font-semibold">Exhaustive Reversal</h1><p className="text-xs text-gray-500">Daily review queue for fading or climactic price extensions. Trend-supported assets are promoted into the review queue as context; only fading or climactic regimes are reversal-ranked.</p></div>
    <div className="flex flex-wrap items-end gap-3 rounded border border-gray-200 bg-gray-50 p-3"><label className="text-xs font-medium text-gray-700">Asset<input value={tickerFilter} onChange={event => setTickerFilter(event.target.value)} placeholder="Ticker" className="mt-1 block w-28 rounded border border-gray-300 bg-white px-2 py-1.5 font-mono text-sm" /></label><label className="text-xs font-medium text-gray-700">Review queue<select value={candidateFilter} onChange={event => setCandidateFilter(event.target.value as CandidateFilter)} className="mt-1 block rounded border border-gray-300 bg-white px-2 py-1.5 text-sm"><option value="all">All candidates</option><option value="complete">Complete evidence</option><option value="incomplete">Incomplete evidence</option><option value="fading_drift">Fading drift</option><option value="climactic_extension">Climactic extension</option><option value="trend_supported">Trend-supported context</option></select></label>{active && <button type="button" onClick={clear} className="rounded border border-gray-300 bg-white px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-yellow-50">Clear filters</button>}<span className="pb-1 text-xs text-gray-500">{candidates.length} review rows · {monitor.length} unresolved assets</span></div>
    <section className="rounded border border-gray-200 bg-white"><div className="border-b border-gray-200 bg-gray-50 px-3 py-2"><h2 className="text-sm font-semibold">Reversal review queue</h2><p className="text-xs text-gray-500">Reversal candidates rank ahead of trend-supported context. A score prioritizes review; it is not a reversal prediction.</p></div>{candidates.length ? <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr>{([ ["Asset", "asset"], ["Review assessment", "assessment"], ["Regime", null], ["Price extension", "extension"], ["Participation", "participation"], ["Reversal flow", "flow"] ] as const).map(([label, key]) => <th key={label} className="px-3 py-2">{key ? <button type="button" onClick={() => toggleSort(key)} className="inline-flex items-center gap-1 whitespace-nowrap hover:text-yellow-500">{label}<span className={sort.key === key ? "text-brand-700" : "text-gray-300"}>{sort.key === key ? sort.asc ? "↑" : "↓" : "↕"}</span></button> : label}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{candidates.map((row: any) => <CandidateRows key={row.ticker} row={row} selected={selected === row.ticker} onSelect={() => setSelected(selected === row.ticker ? null : row.ticker)} />)}</tbody></table></div> : <div className="p-3 text-sm text-gray-500">No reversal candidates match the current filter.</div>}</section>
    <details className="rounded border border-gray-200 bg-white"><summary className="cursor-pointer px-3 py-2 text-sm font-semibold">Unresolved monitor <span className="font-normal text-gray-500">({monitor.length})</span></summary><p className="border-t border-gray-200 px-3 py-2 text-xs text-gray-500">These assets have not established a reversal or trend-supported regime.</p><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-3 py-2">Asset</th><th className="px-3 py-2">Monitor state</th><th className="px-3 py-2">10-day drift</th><th className="px-3 py-2">Participation</th><th className="px-3 py-2">Trend flow</th></tr></thead><tbody className="divide-y divide-gray-100">{monitor.map((row: any) => <MonitorRows key={row.ticker} row={row} selected={selected === row.ticker} onSelect={() => setSelected(selected === row.ticker ? null : row.ticker)} />)}</tbody></table></div></details>
  </div>;
}

function CandidateRows({ row, selected, onSelect }: { row: any; selected: boolean; onSelect: () => void }) { const trace = row.trace ?? {}, stance = number(trace.stance_score), complete = Boolean(trace.evidence_complete), trend = trace.regime === "trend_supported", tone = trend ? "text-blue-700" : stance > 0 ? "text-green-700" : "text-red-700"; return <Fragment><tr onClick={onSelect} className={selected ? "cursor-pointer bg-brand-50" : "cursor-pointer hover:bg-gray-50"}><td className="px-3 py-2 font-mono font-semibold"><Link to="/marketops/state" search={{ symbol: row.ticker }} onClick={event => event.stopPropagation()} className="text-brand-700 underline hover:text-brand-800" title="Open Market State">{row.ticker}</Link></td><td className="px-3 py-2"><div className={`font-semibold ${tone}`}>{trend ? "" : (stance > 0 ? "+" : "") + (stance / 10).toFixed(1)}</div><span className={complete ? "inline-flex rounded border border-green-200 bg-green-50 px-1.5 py-0.5 text-[11px] font-medium text-green-700" : "inline-flex rounded border border-amber-200 bg-amber-50 px-1.5 py-0.5 text-[11px] font-medium text-amber-700"}>{trend ? "Sustained" : complete ? "Complete evidence" : "Incomplete evidence"}</span><div className={`mt-1 text-xs ${tone}`}>{trend ? trace.direction === "BULLISH" ? "Bullish drift" : trace.direction === "BEARISH" ? "Bearish drift" : "Flat drift" : directionLabel(trace)}</div></td><td className="px-3 py-2 text-xs font-medium">{regimeLabel(trace.regime)}</td><td className="px-3 py-2 text-xs">{fixed(trace.price_extension_pct, 2)}%<div className="text-gray-500">{fixed(trace.price_extension_units)}× normal move</div></td><td className="px-3 py-2 text-xs">{trace.regime === "climactic_extension" ? <><span>{fixed(trace.relative_volume_20d)}× 20d volume</span><div className="text-gray-500">climactic</div></> : trace.regime === "trend_supported" ? <><span>{fixed(trace.volume_ratio)}× 5d volume</span><div className="text-blue-700">sustained</div></> : <><span>{fixed(trace.volume_ratio)}× 5d volume</span><div className="text-gray-500">fading</div></>}</td><td className="px-3 py-2 text-xs">{trace.reversal_flow_ratio == null ? "Unavailable" : <><span>{fixed(trace.reversal_flow_ratio)}×</span><div className={trace.flow_eligible ? "text-green-700" : "text-amber-700"}>{trace.flow_eligible ? "confirmed" : "not confirmed"}</div></>}</td></tr>{selected && <DetailRow row={row} colSpan={6} onClose={onSelect} />}</Fragment>; }
function MonitorRows({ row, selected, onSelect }: { row: any; selected: boolean; onSelect: () => void }) { const trace = row.trace ?? {}; return <Fragment><tr onClick={onSelect} className={selected ? "cursor-pointer bg-brand-50" : "cursor-pointer hover:bg-gray-50"}><td className="px-3 py-2 font-mono font-semibold"><Link to="/marketops/state" search={{ symbol: row.ticker }} onClick={event => event.stopPropagation()} className="text-brand-700 underline hover:text-brand-800" title="Open Market State">{row.ticker}</Link></td><td className="px-3 py-2 text-xs font-medium">{regimeLabel(trace.regime)}</td><td className="px-3 py-2 text-xs">{trace.drift_direction === "BULLISH" ? "Downward" : trace.drift_direction === "BEARISH" ? "Upward" : "Flat"}</td><td className="px-3 py-2 text-xs">{trace.volume_ratio ? `${fixed(trace.volume_ratio)}× 5d volume` : "—"}</td><td className="px-3 py-2 text-xs">{trace.trend_flow_ratio == null ? "Unavailable" : `${fixed(trace.trend_flow_ratio)}×`}</td></tr>{selected && <DetailRow row={row} colSpan={5} onClose={onSelect} />}</Fragment>; }
function DetailRow({ row, colSpan, onClose }: { row: any; colSpan: number; onClose: () => void }) { const trace = row.trace ?? {}; return <tr className="bg-brand-50"><td colSpan={colSpan} className="p-3"><div className="rounded border border-brand-200 bg-white p-3 text-xs"><div className="flex justify-between gap-2"><div><strong>{row.ticker} regime trace</strong><div className="mt-1 text-gray-600">{directionLabel(trace)} · {regimeLabel(trace.regime)} · {trace.regime === "trend_supported" ? "trend-supported context" : trace.reversal_candidate ? trace.evidence_complete ? "complete review candidate" : "incomplete review candidate" : "not reversal-ranked"}</div></div><button type="button" onClick={event => { event.stopPropagation(); onClose(); }} className="text-brand-700 underline">Close</button></div><div className="mt-3 grid gap-2 md:grid-cols-3"><div>Extension: <strong>{fixed(trace.price_extension_pct, 2)}%</strong><br />Normalized extension: <strong>{fixed(trace.price_extension_units)}×</strong><br />Persistence: {fixed(trace.persistence_score)} / 100</div><div>Five-day volume: {fixed(trace.volume_ratio)}×<br />Latest / prior 20d: {fixed(trace.relative_volume_20d)}×<br />{trace.regime === "trend_supported" ? <>Trend evidence: <strong>volume sustained</strong><br />Trend flow: <strong>{fixed(trace.trend_flow_ratio)}×</strong></> : <>Regime evidence: {fixed(trace.volume_score)} / 100</>}</div><div>Reversal flow: {fixed(trace.reversal_flow_ratio)}×<br />Trend flow: {fixed(trace.trend_flow_ratio)}×<br />Options-flow extreme: <strong>{trace.options_flow_extreme === "call_volume_extreme" ? "Call-volume extreme" : trace.options_flow_extreme === "put_volume_extreme" ? "Put-volume extreme" : "None"}</strong><br />Put/call volume: {fixed(trace.put_call_volume_ratio)} · {number(trace.total_option_volume).toLocaleString()} contracts<br /><span className="text-gray-500">Context only; aggregate volume does not establish trade direction.</span><br />Reasons: {(trace.reasons ?? []).map(title).join(" · ") || "None"}</div></div><div className="mt-3"><MarketOpsPriceSentimentChart tenantId="tenant-local" symbol={row.ticker} /></div></div></td></tr>; }
